version: '3.8'

networks:
    aws_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                  gateway: 172.16.238.1

services:
    nginx:
        image: nginx:1.21.1
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/
        environment:
            - AWS_DEFAULT_REGION=ap-northeast-1
            - AWS_DEFAULT_OUTPUT=json
            - AWS_ACCESS_KEY_ID=coachtech
            - AWS_SECRET_ACCESS_KEY=coachtech_pass
        extra_hosts:
            - "localstack:172.16.238.1"
            - "coachtech.localstack:172.16.238.1"
        depends_on:
            - php
            - localstack

    php:
        build: ./docker/php
        volumes:
            - ./src:/var/www/

    mysql:
        image: mysql:8.0.26
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        command:
            mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=laravel_user
            - PMA_PASSWORD=laravel_pass
        depends_on:
            - mysql
        ports:
            - 8080:80

    localstack:
        image: localstack/localstack:latest
        container_name: localstack
        environment:
            - SERVICES=s3
            - DEFAULT_REGION=us-east-1
        networks:
            - aws_net
        ports:
            - "8888:8080"
            - "4567-4578:4567-4578"

# awscli
    awscli:
        image: xueshanf/awscli
        environment:
            - AWS_DEFAULT_REGION=ap-northeast-1
            - AWS_DEFAULT_OUTPUT=json
            - AWS_ACCESS_KEY_ID=coachtech
            - AWS_SECRET_ACCESS_KEY=coachtech_pass
        extra_hosts:
            - "localstack:172.16.238.1"
            - "coachtech.localstack:172.16.238.1"
        depends_on:
            - localstack
        entrypoint: aws --endpoint-url=http://localstack:4572 s3 mb s3://coachtech/
        networks:
            - aws_net